# Generated by Django 3.2.7 on 2021-09-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Macrodata',
        ),
    ]
