# Generated by Django 3.2.7 on 2021-09-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_macrodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrodata',
            name='tarix',
            field=models.DateTimeField(),
        ),
    ]
