# Generated by Django 3.2.7 on 2021-09-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_macrodata_tarix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrodata',
            name='tarix',
            field=models.DateField(),
        ),
    ]
